name: Android CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: gradle wrapper
        run: gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Release Bundle
        run: ./gradlew :app:bundleRelease

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v3
        with:
          name: HearThisAndroidReleaseBundle
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Publish to Play Store Internal track
        uses: r0adkll/upload-google-play@v1.0.19
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: org.sil.hearthis
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
